env:
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-empty:
    - error
    - { "allowEmptyCatch": true }
  indent:
    - error
    - 4
    - { "SwitchCase": 1 }
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
