- name: AE Abu Dhabi
  iso: AE
  dns: ae.http-proxy.privateinternetbrowsing.com
  ping: 146.70.37.134
  port: 443
  mace: 80
- name: AU Sydney
  iso: AU
  dns: au-sydney.http-proxy.privateinternetbrowsing.com
  ping: 27.50.87.166
  port: 443
  mace: 80
- name: AU Melbourne
  iso: AU
  dns: aus-melbourne.http-proxy.privateinternetbrowsing.com
  ping: 221.121.142.198
  port: 443
  mace: 80
- name: AT Vienna
  iso: AT
  dns: austria.http-proxy.privateinternetbrowsing.com
  ping: 146.70.28.158
  port: 443
  mace: 80
- name: BE Brussels
  iso: BE
  dns: brussels.http-proxy.privateinternetbrowsing.com
  ping: 91.207.57.46
  port: 443
  mace: 80
- name: CA Montreal
  iso: CA
  dns: ca-montreal.http-proxy.privateinternetbrowsing.com
  ping: 172.98.71.129
  port: 443
  mace: 80
- name: CA Toronto
  iso: CA
  dns: ca-toronto.http-proxy.privateinternetbrowsing.com
  ping: 66.115.142.129
  port: 443
  mace: 80
- name: CA Vancouver
  iso: CA
  dns: ca-vancouver.http-proxy.privateinternetbrowsing.com
  ping: 104.200.150.133
  port: 443
  mace: 80
- name: CZ Prague
  iso: CZ
  dns: czech.http-proxy.privateinternetbrowsing.com
  ping: 212.102.39.164
  port: 443
  mace: 80
- name: DE Berlin
  iso: DE
  dns: de-berlin.http-proxy.privateinternetbrowsing.com
  ping: 37.120.217.22
  port: 443
  mace: 80
- name: DE Frankfurt
  iso: DE
  dns: de-frankfurt.http-proxy.privateinternetbrowsing.com
  ping: 82.102.16.14
  port: 443
  mace: 80
- name: DK Copenhagen
  iso: DK
  dns: denmark.http-proxy.privateinternetbrowsing.com
  ping: 146.70.42.126
  port: 443
  mace: 80
- name: FI Helsinki
  iso: FI
  dns: fi.http-proxy.privateinternetbrowsing.com
  ping: 46.246.34.27
  port: 443
  mace: 80
- name: FR Paris
  iso: FR
  dns: france.http-proxy.privateinternetbrowsing.com
  ping: 146.70.40.198
  port: 443
  mace: 80
- name: HU Budapest
  iso: HU
  dns: hungary.http-proxy.privateinternetbrowsing.com
  ping: 185.252.223.158
  port: 443
  mace: 80
- name: IN Mumbai
  iso: IN
  dns: in.http-proxy.privateinternetbrowsing.com
  ping: 166.0.218.228
  port: 443
  mace: 80
- name: IE Dublin
  iso: IE
  dns: ireland.http-proxy.privateinternetbrowsing.com
  ping: 146.70.48.238
  port: 443
  mace: 80
- name: IL Jerusalem
  iso: IL
  dns: israel.http-proxy.privateinternetbrowsing.com
  ping: 169.150.248.202
  port: 443
  mace: 80
- name: IT Milano
  iso: IT
  dns: italy.http-proxy.privateinternetbrowsing.com
  ping: 217.138.197.230
  port: 443
  mace: 80
- name: JP Tokyo
  iso: JP
  dns: japan.http-proxy.privateinternetbrowsing.com
  ping: 154.47.20.198
  port: 443
  mace: 80
- name: LU Luxembourg
  iso: LU
  dns: lu.http-proxy.privateinternetbrowsing.com
  ping: 37.46.113.190
  port: 443
  mace: 80
- name: NL Amsterdam
  iso: NL
  dns: nl-amsterdam.http-proxy.privateinternetbrowsing.com
  ping: 109.201.152.185
  port: 443
  mace: 80
- name: NO Oslo
  iso: NO
  dns: no.http-proxy.privateinternetbrowsing.com
  ping: 146.70.17.46
  port: 443
  mace: 80
- name: NZ Wellington
  iso: NZ
  dns: nz.http-proxy.privateinternetbrowsing.com
  ping: 221.121.135.166
  port: 443
  mace: 80
- name: PL Warsaw
  iso: PL
  dns: poland.http-proxy.privateinternetbrowsing.com
  ping: 138.199.59.230
  port: 443
  mace: 80
- name: RO Bucharest
  iso: RO
  dns: ro.http-proxy.privateinternetbrowsing.com
  ping: 143.244.54.37
  port: 443
  mace: 80
- name: SG Singapore
  iso: SG
  dns: sg.http-proxy.privateinternetbrowsing.com
  ping: 156.146.57.10
  port: 443
  mace: 80
- name: ES Madrid
  iso: ES
  dns: spain.http-proxy.privateinternetbrowsing.com
  ping: 45.128.39.246
  port: 443
  mace: 80
- name: SE Stockholm
  iso: SE
  dns: sweden.http-proxy.privateinternetbrowsing.com
  ping: 146.70.21.93
  port: 443
  mace: 80
- name: UK London
  iso: UK
  dns: uk-london.http-proxy.privateinternetbrowsing.com
  ping: 212.102.53.136
  port: 443
  mace: 80
- name: UK Manchester
  iso: UK
  dns: uk-manchester.http-proxy.privateinternetbrowsing.com
  ping: 89.249.74.174
  port: 443
  mace: 80
- name: UK Southampton
  iso: UK
  dns: uk-southampton.http-proxy.privateinternetbrowsing.com
  ping: 138.199.28.157
  port: 443
  mace: 80
- name: US Atlanta
  iso: US
  dns: us-atlanta.http-proxy.privateinternetbrowsing.com
  ping: 156.146.47.10
  port: 443
  mace: 80
- name: US Los Angeles
  iso: US
  dns: us-california.http-proxy.privateinternetbrowsing.com
  ping: 146.70.49.187
  port: 443
  mace: 80
- name: US Chicago
  iso: US
  dns: us-chicago.http-proxy.privateinternetbrowsing.com
  ping: 143.244.60.150
  port: 443
  mace: 80
- name: US Denver
  iso: US
  dns: us-denver.http-proxy.privateinternetbrowsing.com
  ping: 37.19.210.100
  port: 443
  mace: 80
- name: US Miami
  iso: US
  dns: us-florida.http-proxy.privateinternetbrowsing.com
  ping: 37.120.157.150
  port: 443
  mace: 80
- name: US Houston
  iso: US
  dns: us-houston.http-proxy.privateinternetbrowsing.com
  ping: 156.146.39.214
  port: 443
  mace: 80
- name: US Las Vegas
  iso: US
  dns: us-lasvegas.http-proxy.privateinternetbrowsing.com
  ping: 45.89.173.245
  port: 443
  mace: 80
- name: US Trenton
  iso: US
  dns: us-newjersey.http-proxy.privateinternetbrowsing.com
  ping: 37.120.202.94
  port: 443
  mace: 80
- name: US New York
  iso: US
  dns: us-newyorkcity.http-proxy.privateinternetbrowsing.com
  ping: 138.199.13.169
  port: 443
  mace: 80
- name: US Seattle
  iso: US
  dns: us-seattle.http-proxy.privateinternetbrowsing.com
  ping: 156.146.49.5
  port: 443
  mace: 80
- name: US Silicon Valley
  iso: US
  dns: us-siliconvalley.http-proxy.privateinternetbrowsing.com
  ping: 66.115.165.65
  port: 443
  mace: 80
- name: US Dallas
  iso: US
  dns: us-texas.http-proxy.privateinternetbrowsing.com
  ping: 156.146.39.83
  port: 443
  mace: 80
- name: US Washington DC
  iso: US
  dns: us-washingtondc.http-proxy.privateinternetbrowsing.com
  ping: 70.32.1.81
  port: 443
  mace: 80
- name: US Phoenix
  iso: US
  dns: us3.http-proxy.privateinternetbrowsing.com
  ping: 107.181.185.115
  port: 443
  mace: 80
